### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by varsha1288** [AWS-South-Wales-User-Group/qldb-bicycle-licence-demo#16]
I am getting this Error. 

Can you please tell me, what am I doing wrong or any prerequisites?

 An error occurred: MyWAFAssociation - AWS WAF couldn?t perform the operation because your resource doesn?t exist. (Service: Wafv2, Status Code: 400, Request ID: 988ba0be-36e1-420f-8889-20614f205c0e, Extended Request ID: null).

**Comment by mlewis7127** [comment]
Ah I think I know why this is. Could you comment out the MyWAFAssociation section and run the sls deploy, then deploy the backend, and then go back, uncomment out the MyWAF Association, and do an `sls deploy` on the apigateway again. I'll look to move this into the backend setup during the week

**Comment by varsha1288** [comment]
Great! Got this to work. Thanks so much!
