### ISSUE TITLE
How to deploy streams-dynamodb and streams-elastic search?

### ISSUE THREAD

**Issue by varsha1288** [AWS-South-Wales-User-Group/qldb-bicycle-licence-demo#18]
Hello,

How to deploy the dynamo db and streams -es folder?

The readme file does not have info about deploying that. However I used commands like before.

Could you please update that in readme.

Thanks,
Varsha

**Comment by varsha1288** [comment]
Post deploying the dynamo-db the search functionality using last name does not seem to work.
Could you please check!

**Comment by mlewis7127** [comment]
I've updated the README. There is a separate qldb-bicycle-demo repo under the AWS South Wales org that has more information. Be careful around charges, especially with the ES service. I have scaled down the instance size to make it less expensive. The search functionality using last name is against Elasticsearch and not DynamoDB. DynamoDB is used on the last Enquiry page to show all licences that have been registered by the logged in user. You can find more details on the QLDBguide documentation pages - https://qldbguide.com/docs/demo/architecture/

**Comment by varsha1288** [comment]
Awesome. Thanks for the information.
